#!/bin/bash
##
## Usage: yabst [options] [VAL1] [VAL2]
##
## Short description in one line.
## Must be run as root.
##
## Options:
##  -h, --help      Display this message.
##  -v, --version   Display version number.
##  -q              Quiet mode.
##
## VAL1 is the first example parameter.
## VAL2 is the second example parameter.
##
## Example:
## yabst -q "lorem ipsum" 123
##

#-------------------#
# GLOBAL VARIABLES  #
#-------------------#
VMAJ=0  # major version
VMIN=1  # minor version
VREV=0  # patch version

QTM=0   # quiet mode flag

VAL1="" # first example parameter
VAL2="" # second example parameter

#------------------#
# GLOBAL FUNCTIONS #
#------------------#
_config() {
  source "$1"
}
_echo() {
  if [ $QTM -eq 0 ]; then
    echo "$1"
  fi
}
_error() {
  echo "$1"
  exit 1
}
_replace(){
  if [ "$#" -eq 3 ]; then
    if [ -e "$1" ]; then
      sed -i 's/'"${2////\\/}"'/'"${3////\\/}"'/g' "$1"
    else
      _error "'$1' is not a valid file."
    fi
  else
    _error "Function needs 3 parameter (file, search, replace)."
  fi
}
_root() {
  if [[ $(whoami) != "root" ]]; then
    _error "This program must be run as root."
  fi
}
_title() {
  if [ $QTM -eq 0 ]; then
    (echo; echo \*\*\* $1 \*\*\*; echo)
  fi
}
_usage(){
  [ "$*" ] && echo "$0: $*"
  sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0"
  exit 2
}
_version() {
  echo "" && echo "$0 version $VMAJ.$VMIN.$VREV"
  echo "Web: http://github.com/teotiger/yabst" && echo ""
  exit 2
}
_write(){
  fname="out.txt"
  if [ ! -z "$2" ]; then
    fname="$2"
  fi

  cat <<EOF > "$fname"
$1
EOF
  chown $SUDO_UID:$SUDO_GID "$fname"
  _echo "File '$fname' created"
}
#--------------------#
# PROGRAMM FUNCTIONS #
#--------------------#
step_01(){
  _title "First program step"
  _echo "First example parameter => $VAL1"
  _echo "Second example parameter => $VAL2"
}
step_02(){
  _title "Second program step"
  text="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat."
  _write "$text" "example.txt"
  _write "$text"
}
step_03(){
  _title "Third program step"
  _config "/etc/lsb-release"
  _echo "$DISTRIB_DESCRIPTION"
  _echo "$DISTRIB_CODENAME"
}
#-----------------------#
# MAIN FUNCTION / START #
#-----------------------#
main() {
  while [ $# -gt 0 ]; do
    case $1 in
    (-h|--help) _usage;;
    (-v|--version) _version;;
    (-q) QTM=1;shift;;
    (--) shift; break;;
    (-*) _usage "$1: unknown option";;
    (*) VAL1="$1"; VAL2="$2"; break;;
    esac
  done
  _root
  if [ -z "$VAL1" ] || [ -z "$VAL2" ]; then
    _usage "required parameter missing"
  fi
  step_01
  step_02
  step_03
}
main "$@"
